### PR TITLE
implement faq page

### PR DESCRIPTION
**Pull request by mistyb01**
## What

> Summary of what you're changing.
- page structure and components
- updated copy and icons
- added link to footer

## How Do

> Implementation choices, reviewer notes, caveats, etc.
- for convenience, I decided to use MUI equivalents of the icons from the figma. will check in with design about it.

## Show Me

> Screenshot of your change, if applicable.
image

### CODE REVIEW

**Review by ybalenko — CHANGES_REQUESTED** [review]
@mistyb01 thank you for the updates! It's a working branch but I wanted to point out that the footer on the home page is broken in **Safari**

Screenshot 2024-08-29 at 14 48 36

**Review by jnakaso — CHANGES_REQUESTED** [review]
yeah, safari is busted
Screen Shot 2024-08-29 at 19 32 10

**Comment by mistyb01** [comment]
^ yikes! I think I know the cause. Will submit a fix tomorrow.

**Review by ybalenko — COMMENTED** [review]
Thank you, @mistyb01 . I reviewed the layout in Safari, and it's now fixed. Another minor suggestion would be to implement the same effect we use in the Oath section, where opening a new section automatically closes the previous one. Confirmed with Jiaqi to have only one section opened at a time and keep consistency.

**Review by jnakaso — APPROVED** [review]
Nicely done.

**Comment by mistyb01** [comment]
Currently facing an issue where the transition goes away once I use the `expanded` and `onChange` props to toggle only one at a time. :/

**Comment by mistyb01** [comment]
cannot figure out why the transition is no longer working in the current version.

**Comment by ybalenko** [comment]
> cannot figure out why the accordion transition is no longer working in the current version.

It works for me in Safari and Chrome. Which browser are you using?

**Comment by jnakaso** [comment]
> cannot figure out why the accordion transition is no longer working in the current version.

works for me

**Review by ybalenko — DISMISSED** [review]

**Pull request merged**
